#!/usr/bin/env bash
# Cluster-free boot test for the baked containerDisk (run build.sh first):
# boots build/disk.qcow2 (via a throwaway overlay) with a SESSION-shaped seed
# generated by the real whistler.cloudinit.build_user_data (ssh mode, i.e.
# desktop=False — what the operator ships for a `mode: ssh, runtime: vm`
# template), then asserts the toolchain over SSH exactly as a user would meet
# it. The NFS home mount fails by design (no gateway outside the cluster); the
# session comes up against the warned-about unmounted home, which is the code
# path's documented fallback.
#
# The sibling of ../../desktops/vm-*-selkies/test.sh. There is nothing to look
# at in a browser here, so KEEP defaults to 0 (tear down); KEEP=1 leaves the VM
# up and tells you how to ssh in.
#
# Env: PORT (host ssh forward, 2222), KEEP (0), TEST_USER (marma).
set -euo pipefail
cd "$(dirname "$0")"

PORT="${PORT:-2222}"
KEEP="${KEEP:-0}"
TEST_USER="${TEST_USER:-marma}"
BUILD_DIR="$PWD/build"
HTTP_PORT=8099

[ -s "$BUILD_DIR/disk.qcow2" ] || { echo "ERROR: no build/disk.qcow2 — run build.sh first" >&2; exit 1; }

SEED_DIR="$BUILD_DIR/test-seed"
rm -rf "$SEED_DIR" && mkdir -p "$SEED_DIR"

ssh-keygen -q -t ed25519 -N "" -f "$SEED_DIR/id" <<<y >/dev/null 2>&1 || true

# The real per-session document. The gateway host is unresolvable on purpose —
# exercises the unmounted-home fallback.
../../.venv/bin/python - "$TEST_USER" "$(cat "$SEED_DIR/id.pub")" > "$SEED_DIR/user-data" <<'EOF'
import sys
from whistler.cloudinit import build_user_data
print(build_user_data(
    username=sys.argv[1], uid=1000,
    ssh_keys=[sys.argv[2]],
    hostname="devbasetest",
    nfs_host="whistler-storage-nowhere.invalid",
), end="")
EOF
printf 'instance-id: whistler-devbasetest\nlocal-hostname: devbasetest\n' > "$SEED_DIR/meta-data"

CTR="whistler-devbase-boottest"
docker rm -f "$CTR" >/dev/null 2>&1 || true
cleanup() { [ "$KEEP" = "1" ] || docker rm -f "$CTR" >/dev/null 2>&1 || true; }
trap cleanup EXIT INT TERM

# Reuse the bake toolbox image; overlay so the baked disk stays pristine.
docker run -d --name "$CTR" \
  --device /dev/kvm \
  --user "$(id -u):$(id -g)" --group-add "$(stat -c %g /dev/kvm)" \
  -v "$BUILD_DIR:/build" -v "$SEED_DIR:/seed:ro" \
  -p "127.0.0.1:$PORT:$PORT" \
  --entrypoint /bin/sh \
  whistler-vm-bake -c "
    set -eu
    qemu-img create -f qcow2 -b /build/disk.qcow2 -F qcow2 /tmp/test.qcow2 >/dev/null
    python3 -m http.server --bind 127.0.0.1 --directory /seed $HTTP_PORT >/dev/null 2>&1 &
    exec qemu-system-x86_64 \
      -enable-kvm -cpu host -smp 4 -m 4096 \
      -drive file=/tmp/test.qcow2,if=virtio,format=qcow2 \
      -netdev user,id=n0,hostfwd=tcp:0.0.0.0:$PORT-:22 \
      -device virtio-net-pci,netdev=n0 \
      -smbios 'type=1,serial=ds=nocloud-net;s=http://10.0.2.2:$HTTP_PORT/' \
      -display none -serial file:/build/test-console.log
  " >/dev/null

SSH=(ssh -q -i "$SEED_DIR/id" -p "$PORT" -o StrictHostKeyChecking=no
     -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 "$TEST_USER@localhost")

echo "booting (console: $BUILD_DIR/test-console.log) ..."
for i in $(seq 1 150); do
  "${SSH[@]}" true 2>/dev/null && break
  if ! docker inspect -f '{{.State.Running}}' "$CTR" 2>/dev/null | grep -q true; then
    echo "FAIL: VM exited early — tail of test-console.log:" >&2
    tail -40 "$BUILD_DIR/test-console.log" >&2
    exit 1
  fi
  [ "$i" = 150 ] && { echo "FAIL: sshd never reachable — tail of test-console.log:" >&2
                      tail -60 "$BUILD_DIR/test-console.log" >&2; exit 1; }
  sleep 2
done
echo "PASS: sshd reachable as $TEST_USER (cloud-init created the session user)"

rc=0
check() {  # check <label> <remote sh>
  # pipefail on the REMOTE shell: nearly every check below ends in `| head -1`
  # or similar, and without it a missing binary is masked by the exit status of
  # the tail of the pipeline — which is exactly how an nvcc-not-on-PATH image
  # once reported PASS while printing "command not found".
  if out=$("${SSH[@]}" "set -o pipefail; $2" 2>&1); then
    printf 'PASS: %-28s %s\n' "$1" "$(echo "$out" | head -1)"
  else
    printf 'FAIL: %-28s %s\n' "$1" "$(echo "$out" | tail -2 | tr '\n' ' ')" >&2
    rc=1
  fi
}

check "release receipt"   'head -1 /etc/whistler-devbase-release'
check "python 3.14"       'python3 --version | grep -q "^Python 3\.14\." && python3 --version'
check "python headers"    'python3 -c "import sysconfig,os;p=sysconfig.get_paths()[\"include\"]+\"/Python.h\";print(p);exit(0 if os.path.exists(p) else 1)"'
check "clang C++"         'printf "#include <iostream>\nint main(){std::cout<<\"clang ok\"<<std::endl;}\n" > /tmp/t.cc && clang++ /tmp/t.cc -o /tmp/t && /tmp/t'
check "clang sanitizers"  'clang++ -fsanitize=address,undefined /tmp/t.cc -o /tmp/ts && /tmp/ts'
check "clangd"            'clangd --version'
check "gcc/g++"           'g++ --version | head -1'
check "cmake+ninja"       'cmake --version | head -1 && ninja --version'
check "pixi"              'pixi --version'
check "pixi on PATH (login)" 'bash -lc "case :\$PATH: in *:\$HOME/.pixi/bin:*) echo \"\$HOME/.pixi/bin on PATH\";; *) exit 1;; esac"'
# The hook itself, not `run-parts /etc/update-motd.d`: run-parts exits nonzero
# if ANY motd script in the dir fails (stock Ubuntu ones do, variably), which
# tells us nothing about ours. Captured into a variable rather than piped into
# `grep -q`, which exits at the first match and SIGPIPEs the writer — under the
# pipefail above that reads as a failure.
check "motd hook"         'out=$(/etc/update-motd.d/99-whistler-devbase); case "$out" in *"Whistler devbase"*) echo "motd prints the release";; *) exit 1;; esac'
check "git/tmux/vim/jq"   'command -v git tmux vim jq | tr "\n" " "'
check "nfs client"        'command -v mount.nfs4'
check "no desktop baked"  '! command -v Xvfb >/dev/null && ! systemctl list-unit-files 2>/dev/null | grep -q whistler-streamer && echo "no X, no streamer (server image)"'

# CUDA variants. nvcc needs no GPU (it is a cross-compiler — this compiles to
# PTX), which is exactly why it can be tested here; nvidia-smi cannot work
# under plain qemu with no passthrough device, so it is only reported.
if "${SSH[@]}" 'test -x /usr/local/cuda/bin/nvcc' 2>/dev/null; then
  # Every check here runs over `ssh <host> <cmd>`, i.e. a NON-login shell that
  # never sources profile.d — so a bare `nvcc` succeeding is itself the
  # regression test for the /etc/environment PATH.
  check "nvcc"            'nvcc --version | tail -2 | head -1'
  # And it must resolve to the real toolkit path: nvcc finds its headers
  # relative to argv[0] without following symlinks, so a /usr/local/bin/nvcc
  # shim would compile-fail on cuda_runtime.h (it did).
  check "nvcc real path"  'command -v nvcc | grep "^/usr/local/cuda/bin/nvcc$"'
  check "nvcc compiles"   'printf "__global__ void k(float*p){p[threadIdx.x]=1.f;}\n" > /tmp/t.cu && nvcc -ptx /tmp/t.cu -o /tmp/t.ptx && head -c 24 /tmp/t.ptx'
  check "CUDA dev libs"   'test -f /usr/local/cuda/targets/x86_64-linux/include/cublas_v2.h && echo "cuBLAS headers present"'
  check "cuda on ld path" 'ldconfig -p | grep -c "libcudart\|libcublas" | xargs -I{} echo "{} CUDA libs in ld cache"'
fi
if "${SSH[@]}" 'command -v nvidia-smi >/dev/null' 2>/dev/null; then
  echo "note: nvidia-smi present (GPU runtime baked); it cannot run here — no passthrough GPU under this qemu"
fi

# Regression guard shared with the desktop images: once the NFS home shadows
# ~/.ssh/authorized_keys, auth must still work via the root disk's
# /etc/ssh/authorized_keys.d — which sshd StrictModes refuses if the bake tar
# ever restores group-writable modes onto /etc.
check "home mount stand-in" "mountpoint -q /home/$TEST_USER || { sudo mount -t tmpfs -o mode=0755 tmpfs /home/$TEST_USER && sudo chown $TEST_USER: /home/$TEST_USER && echo 'tmpfs home mounted'; }"
check "ssh auth post-mount" 'echo "authorized_keys.d path still authenticates"'

if [ "$KEEP" = "1" ]; then
  echo
  echo "VM left running. ssh -i $SEED_DIR/id -p $PORT $TEST_USER@localhost"
  echo "Tear down with: docker rm -f $CTR"
fi
exit "$rc"
