{{- if .Values.guacd.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-guacd
  namespace: {{ .Release.Namespace }}
  labels:
    app: whistler-guacd
spec:
  replicas: {{ .Values.guacd.replicaCount }}
  selector:
    matchLabels:
      app: whistler-guacd
  template:
    metadata:
      labels:
        app: whistler-guacd
    spec:
      automountServiceAccountToken: false
      containers:
        - name: guacd
          image: {{ .Values.guacd.image | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4822
              name: guacd
          {{- with .Values.guacd.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
