{{- if .Values.guacd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-guacd
  namespace: {{ .Release.Namespace }}
  labels:
    app: whistler-guacd
spec:
  type: ClusterIP
  selector:
    app: whistler-guacd
  ports:
    - name: guacd
      port: 4822
      targetPort: 4822
{{- end }}
