apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: whistler
build:
  artifacts:
    - image: whistler
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: whistler
        chartPath: charts/whistler
        namespace: whistler
        createNamespace: true
        valuesFiles:
          - charts/whistler/values.yaml
        setValues:
          whistler.auth.allowAny: false
          server.service.type: NodePort
          server.service.nodePort: 30022
          userVolume.accessMode: ReadWriteOnce
          userVolume.size: 10Mi
          whistler.volumes[0].name: data
          whistler.volumes[0].persistentVolumeClaim.claimName: whistler-data-pvc
          whistler.volumes[1].name: data2
          whistler.volumes[1].persistentVolumeClaim.claimName: whistler-data2-pvc
          # Example: Configure securityContext for a user
          whistler.users[0].name: marma
          whistler.users[0].publicKeys[0]: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMNj07CelG2QAh7IogB+vlS4tRjuxOTr3mt0z3fX8jlX marma"
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_whistler}}"
          image.tag: "{{.IMAGE_TAG_whistler}}"
