#!/usr/bin/env bash
# Cluster-free boot test for the baked containerDisk (run build.sh first):
# boots build/disk.qcow2 (via a throwaway overlay) with a SESSION-shaped seed
# generated by the real whistler.cloudinit.build_user_data (desktop mode), and
# passes when the in-guest Selkies serves HTTP on the forwarded port — i.e.
# the exact cloud-init document the operator would ship starts the streamer
# and the per-user desktop unit. The SMB home mount fails by design (no
# gateway outside the cluster); the session starts against the warned-about
# unmounted home, which is the code path's documented fallback.
#
# PASS leaves the VM up for a browser check at http://localhost:8082/
# (design/creating_desktops.md §6 step 5) until Ctrl-C — set KEEP=0 to tear
# down immediately (CI mode).
set -euo pipefail
cd "$(dirname "$0")"

PORT="${PORT:-8082}"
KEEP="${KEEP:-1}"
TEST_USER="${TEST_USER:-marma}"
BUILD_DIR="$PWD/build"
HTTP_PORT=8099

[ -s "$BUILD_DIR/disk.qcow2" ] || { echo "ERROR: no build/disk.qcow2 — run build.sh first" >&2; exit 1; }

SEED_DIR="$BUILD_DIR/test-seed"
rm -rf "$SEED_DIR" && mkdir -p "$SEED_DIR"

# Throwaway keypair: the post-PASS probe SSHes in (like the portal's web
# terminal does) to check the XFCE session actually runs in the streamer's X.
ssh-keygen -q -t ed25519 -N "" -f "$SEED_DIR/id" <<<y >/dev/null 2>&1 || true

# The real per-session document (desktop mode). The gateway host is
# unresolvable on purpose — exercises the unmounted-home fallback.
../../.venv/bin/python - "$TEST_USER" "$(cat "$SEED_DIR/id.pub")" > "$SEED_DIR/user-data" <<'EOF'
import sys
from whistler.cloudinit import build_user_data
print(build_user_data(
    username=sys.argv[1], uid=1000,
    ssh_keys=[sys.argv[2]],
    hostname="boottest",
    smb_host="whistler-storage-nowhere.invalid",
    smb_password="unused",
    desktop=True,
    streamer_env={},
    display_port=8082,
), end="")
EOF
printf 'instance-id: whistler-boottest\nlocal-hostname: boottest\n' > "$SEED_DIR/meta-data"

CTR="whistler-vm-boottest"
docker rm -f "$CTR" >/dev/null 2>&1 || true
cleanup() { docker rm -f "$CTR" >/dev/null 2>&1 || true; }
trap cleanup EXIT INT TERM

# Reuse the bake toolbox image; overlay so the baked disk stays pristine.
# hostfwd exposes the guest's Selkies (always :8082 in-guest here) on the
# container's $PORT, published to the host loopback.
docker run -d --name "$CTR" \
  --device /dev/kvm \
  --user "$(id -u):$(id -g)" --group-add "$(stat -c %g /dev/kvm)" \
  -v "$BUILD_DIR:/build" -v "$SEED_DIR:/seed:ro" \
  -p "127.0.0.1:$PORT:$PORT" -p "127.0.0.1:2222:2222" \
  --entrypoint /bin/sh \
  whistler-vm-bake -c "
    set -eu
    qemu-img create -f qcow2 -b /build/disk.qcow2 -F qcow2 /tmp/test.qcow2 >/dev/null
    python3 -m http.server --bind 127.0.0.1 --directory /seed $HTTP_PORT >/dev/null 2>&1 &
    exec qemu-system-x86_64 \
      -enable-kvm -cpu host -smp 2 -m 3072 \
      -drive file=/tmp/test.qcow2,if=virtio,format=qcow2 \
      -netdev user,id=n0,hostfwd=tcp:0.0.0.0:$PORT-:8082,hostfwd=tcp:0.0.0.0:2222-:22 \
      -device virtio-net-pci,netdev=n0 \
      -smbios 'type=1,serial=ds=nocloud-net;s=http://10.0.2.2:$HTTP_PORT/' \
      -display none -serial file:/build/test-console.log
  " >/dev/null

probe_desktop() {
  # The HTTP 200 only proves the streamer; this proves the per-user session
  # unit: XFCE alive (and staying alive) with windows in the streamer's X.
  local ssh_cmd=(ssh -q -i "$SEED_DIR/id" -p 2222 -o StrictHostKeyChecking=no
                 -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5
                 "$TEST_USER@localhost")
  for i in $(seq 1 60); do
    "${ssh_cmd[@]}" true 2>/dev/null && break
    [ "$i" = 60 ] && { echo "FAIL: sshd never reachable" >&2; return 1; }
    sleep 2
  done
  # Stand-in for the SMB share landing (no gateway outside the cluster):
  # a writable tmpfs on the mountpoint releases the session script's
  # wait-for-mount and lets XFCE keep a real $HOME — without it the session
  # starts against the root-owned mountpoint and exits on .ICEauthority.
  "${ssh_cmd[@]}" "mountpoint -q /home/$TEST_USER || { sudo mount -t tmpfs -o mode=0755 tmpfs /home/$TEST_USER && sudo chown $TEST_USER: /home/$TEST_USER; }" \
    || { echo "FAIL: could not fake-mount the home" >&2; return 1; }
  # Regression check: a FRESH connection must still authenticate now that
  # ~/.ssh/authorized_keys is shadowed by the mount — i.e. the root-disk
  # /etc/ssh/authorized_keys.d path works (StrictModes once refused it when
  # the bake tar restored group-writable modes onto /etc).
  "${ssh_cmd[@]}" true 2>/dev/null \
    || { echo "FAIL: ssh auth broke once the home mount shadowed ~/.ssh" >&2; return 1; }
  for i in $(seq 1 45); do
    if "${ssh_cmd[@]}" "pgrep -x xfce4-session >/dev/null" 2>/dev/null; then
      sleep 10  # it must survive, not just appear
      local windows
      windows=$("${ssh_cmd[@]}" \
        "pgrep -x xfce4-session >/dev/null && DISPLAY=:0 xdotool search --name '' getwindowname %@ 2>/dev/null | grep -c ." ) \
        || { echo "FAIL: xfce4-session died shortly after starting" >&2; return 1; }
      echo "PASS: xfce4-session running, $windows window(s) in the streamer X, ssh sane post-mount"
      return 0
    fi
    sleep 2
  done
  echo "FAIL: xfce4-session never appeared (streamer up, desktop unit didn't run)" >&2
  return 1
}

echo "booting (console: $BUILD_DIR/test-console.log) ..."
for i in $(seq 1 120); do
  if curl -fsS -o /dev/null "http://localhost:$PORT/" 2>/dev/null; then
    echo "PASS: Selkies serving on http://localhost:$PORT/"
    rc=0
    probe_desktop || rc=1
    if [ "$KEEP" = "1" ]; then
      echo "VM left running for a browser check — Ctrl-C to tear down."
      docker wait "$CTR" >/dev/null
    fi
    exit "$rc"
  fi
  # A dead container means qemu exited — fail fast with the console tail.
  if ! docker inspect -f '{{.State.Running}}' "$CTR" 2>/dev/null | grep -q true; then
    echo "FAIL: VM exited early — tail of test-console.log:" >&2
    tail -40 "$BUILD_DIR/test-console.log" >&2
    exit 1
  fi
  sleep 2
done
echo "FAIL: Selkies never answered on :$PORT — tail of test-console.log:" >&2
tail -60 "$BUILD_DIR/test-console.log" >&2
exit 1
