#!/usr/bin/env bash
# Cluster-free boot test for the baked containerDisk (run build.sh first):
# boots build/disk.qcow2 (via a throwaway overlay) with a SESSION-shaped seed
# generated by the real whistler.cloudinit.build_user_data (desktop mode), and
# passes when the in-guest Selkies serves HTTP on the forwarded port — i.e. the
# exact cloud-init document the operator would ship starts the streamer and the
# per-user GNOME session. The NFS home mount fails by design (no gateway outside
# the cluster); the session starts against the warned-about unmounted home,
# which is the code path's documented fallback.
#
# GNOME differences from ../vm-xfce-selkies/test.sh: the seed sets
# SELKIES_H264_STREAMING_MODE=true (mutter is a GL compositor — see the streamer
# and README), and the desktop probe asserts `gnome-shell` is running instead of
# `xfce4-session`. The HTTP 200 proves only the streamer; the SSH probe proves
# the per-user Shell actually came up in the streamer's X.
#
# IMPORTANT — the protocol/HTTP check can't see frame coherence. Streaming-mode
# black-static-window bugs and llvmpipe GTK4 garbage only show in a real decoded
# stream, so PASS still leaves the VM up for a browser check at
# http://localhost:8082/ (design/creating_desktops.md §6 step 5) until Ctrl-C —
# set KEEP=0 to tear down immediately (CI mode).
set -euo pipefail
cd "$(dirname "$0")"

PORT="${PORT:-8082}"
KEEP="${KEEP:-1}"
TEST_USER="${TEST_USER:-marma}"
BUILD_DIR="$PWD/build"
HTTP_PORT=8099
QMP_PORT="${QMP_PORT:-4444}"

[ -s "$BUILD_DIR/disk.qcow2" ] || { echo "ERROR: no build/disk.qcow2 — run build.sh first" >&2; exit 1; }

SEED_DIR="$BUILD_DIR/test-seed"
rm -rf "$SEED_DIR" && mkdir -p "$SEED_DIR"

# Throwaway keypair: the post-PASS probe SSHes in (like the portal's web
# terminal does) to check the GNOME session actually runs in the streamer's X.
ssh-keygen -q -t ed25519 -N "" -f "$SEED_DIR/id" <<<y >/dev/null 2>&1 || true

# The real per-session document (desktop mode). The gateway host is
# unresolvable on purpose — exercises the unmounted-home fallback.
# streamer_env pins H264 streaming mode on, matching what a vm-gnome template
# must set (mutter emits no damage for static content).
../../.venv/bin/python - "$TEST_USER" "$(cat "$SEED_DIR/id.pub")" > "$SEED_DIR/user-data" <<'EOF'
import sys
from whistler.cloudinit import build_user_data
print(build_user_data(
    username=sys.argv[1], uid=1000,
    ssh_keys=[sys.argv[2]],
    hostname="boottest",
    nfs_host="whistler-storage-nowhere.invalid",
    desktop=True,
    streamer_env={"SELKIES_H264_STREAMING_MODE": "true"},
    display_port=8082,
), end="")
EOF
printf 'instance-id: whistler-boottest\nlocal-hostname: boottest\n' > "$SEED_DIR/meta-data"

CTR="whistler-vm-gnome-boottest"
docker rm -f "$CTR" >/dev/null 2>&1 || true
cleanup() { docker rm -f "$CTR" >/dev/null 2>&1 || true; }
trap cleanup EXIT INT TERM

# Reuse the bake toolbox image; overlay so the baked disk stays pristine.
# hostfwd exposes the guest's Selkies (always :8082 in-guest here) on the
# container's $PORT, published to the host loopback. GNOME wants a bit more RAM
# than XFCE under llvmpipe — 4G.
docker run -d --name "$CTR" \
  --device /dev/kvm \
  --user "$(id -u):$(id -g)" --group-add "$(stat -c %g /dev/kvm)" \
  -v "$BUILD_DIR:/build" -v "$SEED_DIR:/seed:ro" \
  -p "127.0.0.1:$PORT:$PORT" -p "127.0.0.1:2222:2222" \
  -p "127.0.0.1:$QMP_PORT:$QMP_PORT" \
  --entrypoint /bin/sh \
  whistler-vm-bake -c "
    set -eu
    qemu-img create -f qcow2 -b /build/disk.qcow2 -F qcow2 /tmp/test.qcow2 >/dev/null
    python3 -m http.server --bind 127.0.0.1 --directory /seed $HTTP_PORT >/dev/null 2>&1 &
    exec qemu-system-x86_64 \
      -enable-kvm -cpu host -smp 2 -m 4096 \
      -drive file=/tmp/test.qcow2,if=virtio,format=qcow2 \
      -netdev user,id=n0,hostfwd=tcp:0.0.0.0:$PORT-:8082,hostfwd=tcp:0.0.0.0:2222-:22 \
      -device virtio-net-pci,netdev=n0 \
      -smbios 'type=1,serial=ds=nocloud-net;s=http://10.0.2.2:$HTTP_PORT/' \
      -qmp tcp:0.0.0.0:$QMP_PORT,server=on,wait=off \
      -display none -serial file:/build/test-console.log
  " >/dev/null

probe_desktop() {
  # The HTTP 200 only proves the streamer; this proves the per-user session
  # unit: gnome-shell alive (and staying alive) with windows in the streamer's X.
  local ssh_cmd=(ssh -q -i "$SEED_DIR/id" -p 2222 -o StrictHostKeyChecking=no
                 -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5
                 "$TEST_USER@localhost")
  for i in $(seq 1 60); do
    "${ssh_cmd[@]}" true 2>/dev/null && break
    [ "$i" = 60 ] && { echo "FAIL: sshd never reachable" >&2; return 1; }
    sleep 2
  done
  # Stand-in for the NFS export landing (no gateway outside the cluster):
  # a writable tmpfs on the mountpoint releases the session script's
  # wait-for-mount and lets GNOME keep a real $HOME — without it the session
  # starts against the root-owned mountpoint and struggles on dconf/keyring.
  "${ssh_cmd[@]}" "mountpoint -q /home/$TEST_USER || { sudo mount -t tmpfs -o mode=0755 tmpfs /home/$TEST_USER && sudo chown $TEST_USER: /home/$TEST_USER; }" \
    || { echo "FAIL: could not fake-mount the home" >&2; return 1; }
  # Regression check: a FRESH connection must still authenticate now that
  # ~/.ssh/authorized_keys is shadowed by the mount — i.e. the root-disk
  # /etc/ssh/authorized_keys.d path works (StrictModes once refused it when
  # the bake tar restored group-writable modes onto /etc).
  "${ssh_cmd[@]}" true 2>/dev/null \
    || { echo "FAIL: ssh auth broke once the home mount shadowed ~/.ssh" >&2; return 1; }
  # gnome-shell takes longer to come up under llvmpipe than XFCE; give it room.
  for i in $(seq 1 60); do
    if "${ssh_cmd[@]}" "pgrep -x gnome-shell >/dev/null" 2>/dev/null; then
      sleep 12  # it must survive, not just appear (a bad session dies fast)
      local windows
      windows=$("${ssh_cmd[@]}" \
        "pgrep -x gnome-shell >/dev/null && DISPLAY=:0 xdotool search --name '' getwindowname %@ 2>/dev/null | grep -c ." ) \
        || { echo "FAIL: gnome-shell died shortly after starting" >&2; return 1; }
      echo "PASS: gnome-shell running, $windows window(s) in the streamer X, ssh sane post-mount"
      echo "NOTE: HTTP/window checks can't see frame coherence — do the browser check below."
      probe_power_menu || return 1
      return 0
    fi
    sleep 2
  done
  echo "FAIL: gnome-shell never appeared (streamer up, desktop unit didn't run)" >&2
  echo "      Check 'journalctl -u whistler-desktop@$TEST_USER' in the guest. If" >&2
  echo "      it's dying on login1/systemd-run, enable the documented /run/systemd" >&2
  echo "      shadow fallback in whistler-desktop@.service." >&2
  return 1
}

# The data WebSocket, not just the page. /websockets is where selkies does its
# per-connection setup, and a crash in there drops the socket before a single
# frame while `/` keeps answering 200 — the client then reloads the page on a
# ~6s loop, and a session the portal calls Ready never shows a desktop. That is
# exactly how the CUDA image behaved on a GPU-less boot (this one's): GPUtil
# parsed the driver-less nvidia-smi's error text and raised inside the handler
# — see the no-GPU branch in guest/usr/local/bin/whistler-streamer. Stdlib
# handshake, then hold the socket open: a close or EOF is the failure, silence
# is a pass (an idle streamer sends nothing).
probe_stream_socket() {
  ../../.venv/bin/python - "$PORT" 8 <<'WSPROBE' || { echo "FAIL: data WebSocket did not survive — check 'journalctl -u whistler-streamer' in the guest" >&2; return 1; }
import base64, os, socket, sys, time

port, hold = int(sys.argv[1]), float(sys.argv[2])
key = base64.b64encode(os.urandom(16)).decode()
sock = socket.create_connection(("localhost", port), timeout=15)
sock.sendall((
    "GET /websockets HTTP/1.1\r\n"
    f"Host: localhost:{port}\r\n"
    "Upgrade: websocket\r\nConnection: Upgrade\r\n"
    f"Sec-WebSocket-Key: {key}\r\nSec-WebSocket-Version: 13\r\n\r\n"
).encode())

head = b""
while b"\r\n\r\n" not in head:
    chunk = sock.recv(4096)
    if not chunk:
        sys.exit("no response to the WebSocket handshake")
    head += chunk
status = head.split(b"\r\n")[0].decode(errors="replace")
if " 101 " not in status:
    sys.exit(f"handshake refused: {status}")

sock.settimeout(1.0)
deadline = time.monotonic() + hold
while time.monotonic() < deadline:
    try:
        if sock.recv(65536) == b"":
            sys.exit("server closed the data WebSocket")
    except socket.timeout:
        pass
print(f"PASS: data WebSocket stayed up for {hold:.0f}s")
WSPROBE
}

# Whistler stops a VM by halting it, and that is KubeVirt pressing the virtual
# ACPI power button and destroying the domain when the grace period runs out
# (whistler.vm.shutdownGraceSeconds, 30s). The budget only buys a clean
# unmount if the guest ACTS on that button: with nothing handling it — or a
# desktop power manager sitting on the logind inhibitor — the guest is simply
# killed when the window closes, every time, and $HOME (ext4 on a virtio-blk
# disk) comes back needing journal recovery. It is also what `Power off` in
# the desktop menu ends up doing, so this covers both.
#
# `system_powerdown` over QMP is the same press. qemu exits when the guest
# actually powers off, so the container stopping is the signal, and how long
# it took is the number worth printing: this is a check on the guest, not on
# the timeout.
probe_graceful_shutdown() {
  local budget=30 started elapsed
  ../../.venv/bin/python - "$QMP_PORT" <<'QMPPROBE' || { echo "FAIL: could not ask qemu for an ACPI shutdown" >&2; return 1; }
import json, socket, sys

sock = socket.create_connection(("localhost", int(sys.argv[1])), timeout=15)
conn = sock.makefile("rwb")
conn.readline()  # QMP greeting


def run(command):
    conn.write((json.dumps({"execute": command}) + "\n").encode())
    conn.flush()
    while True:
        line = conn.readline()
        if not line:
            sys.exit(f"qemu closed the QMP socket during {command}")
        message = json.loads(line)
        if "error" in message:
            sys.exit(f"{command}: {message['error']}")
        if "return" in message:
            return message["return"]
        # anything else is an asynchronous event; keep reading


run("qmp_capabilities")
run("system_powerdown")
QMPPROBE
  started=$(date +%s)
  for _ in $(seq 1 "$budget"); do
    if ! docker inspect -f '{{.State.Running}}' "$CTR" 2>/dev/null | grep -q true; then
      elapsed=$(( $(date +%s) - started ))
      echo "PASS: guest powered off ${elapsed}s after the ACPI button"
      return 0
    fi
    sleep 1
  done
  echo "FAIL: guest ignored the ACPI power button for ${budget}s — a stop would" >&2
  echo "      destroy the domain under it and $HOME would need fsck. Check" >&2
  echo "      'systemctl show -p HandlePowerKey systemd-logind' and whether a" >&2
  echo "      power manager holds a handle-power-key inhibitor, in the guest." >&2
  tail -20 "$BUILD_DIR/test-console.log" >&2
  return 1
}

# What the system menu will offer. Both answers are asked of the guest exactly
# the way gnome-shell asks them, on the desktop's own session bus:
#
#   CanShutdown -> true   Power Off and Restart appear. gnome-shell gates both
#                         on this one call to org.gnome.SessionManager, and
#                         since this image runs gnome-shell WITHOUT
#                         gnome-session, nothing owned that name and the call
#                         threw — so the menu lost both items with no error
#                         anywhere, while Suspend (which asks logind directly)
#                         stayed. whistler-session-manager owns it now.
#   CanSuspend  -> no     Suspend is hidden, deliberately: a suspended KubeVirt
#                         guest keeps its VMI Running with a frozen desktop and
#                         Whistler has no way to wake it.
probe_power_menu() {
  local ssh_cmd=(ssh -q -i "$SEED_DIR/id" -p 2222 -o StrictHostKeyChecking=no
                 -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5
                 "$TEST_USER@localhost")
  local can_shutdown can_suspend rc=0
  # The desktop's bus is dbus-run-session's, not one XDG_RUNTIME_DIR knows
  # about, so the address is read out of the Shell's own environment. Every
  # step is checked: an unset address would otherwise fall through to the
  # ambient bus and report a confident answer about the wrong session.
  can_shutdown=$("${ssh_cmd[@]}" 'p=$(pgrep -x gnome-shell | head -1); [ -n "$p" ] || { echo "no gnome-shell process"; exit 1; }; a=$(tr "\0" "\n" < /proc/$p/environ | sed -n "s/^DBUS_SESSION_BUS_ADDRESS=//p"); [ -n "$a" ] || { echo "no session bus address in gnome-shell pid $p"; exit 1; }; DBUS_SESSION_BUS_ADDRESS="$a" gdbus call --session --dest org.gnome.SessionManager --object-path /org/gnome/SessionManager --method org.gnome.SessionManager.CanShutdown' 2>&1) || true
  case "$can_shutdown" in
    *true*) echo "PASS: system menu can power off (CanShutdown -> true)" ;;
    *) echo "FAIL: CanShutdown said '$can_shutdown' — the menu will have no" >&2
       echo "      Power Off or Restart. Is whistler-session-manager running" >&2
       echo "      (python3-gi installed)?" >&2
       rc=1 ;;
  esac
  can_suspend=$("${ssh_cmd[@]}" 'gdbus call --system --dest org.freedesktop.login1 --object-path /org/freedesktop/login1 --method org.freedesktop.login1.Manager.CanSuspend' 2>&1) || true
  case "$can_suspend" in
    *no*) echo "PASS: suspend refused, so the menu will not offer it" ;;
    *) echo "FAIL: CanSuspend said '$can_suspend' — the menu will offer a" >&2
       echo "      suspend this VM cannot be woken from (polkit rule missing?)" >&2
       rc=1 ;;
  esac
  return "$rc"
}

echo "booting (console: $BUILD_DIR/test-console.log) ..."
for i in $(seq 1 120); do
  if curl -fsS -o /dev/null "http://localhost:$PORT/" 2>/dev/null; then
    echo "PASS: Selkies serving on http://localhost:$PORT/"
    rc=0
    probe_stream_socket || rc=1
    probe_desktop || rc=1
    if [ "$KEEP" = "1" ]; then
      # probe_graceful_shutdown powers the guest off, so it is the one thing
      # that cannot run while the VM is being kept for the browser check.
      echo "SKIP: graceful-shutdown probe (VM kept; KEEP=0 runs it)"
      echo "VM left running for a browser check — Ctrl-C to tear down."
      docker wait "$CTR" >/dev/null
    else
      probe_graceful_shutdown || rc=1
    fi
    exit "$rc"
  fi
  # A dead container means qemu exited — fail fast with the console tail.
  if ! docker inspect -f '{{.State.Running}}' "$CTR" 2>/dev/null | grep -q true; then
    echo "FAIL: VM exited early — tail of test-console.log:" >&2
    tail -40 "$BUILD_DIR/test-console.log" >&2
    exit 1
  fi
  sleep 2
done
echo "FAIL: Selkies never answered on :$PORT — tail of test-console.log:" >&2
tail -60 "$BUILD_DIR/test-console.log" >&2
exit 1
